# Generated by Django 3.2.5 on 2021-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Toolbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField()),
                (
                    "tools",
                    models.ManyToManyField(related_name="toolboxes", to="query.Tool"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="toolbox",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="query_toolbox_unique_name_version"
            ),
        ),
    ]
