exclude: '.git'
default_stages: [Nonepre-commitNone]

ci:
  autofix_prs: false
  skip:
    - oxipng

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.2
    hooks:
      - id: oxipng
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: 'v0.11.0'
  #   hooks:
  #     - id: markdownlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict # validate no merge conflict strings
      - id: check-json # validate json
      - id: check-yaml # validate yaml
      - id: check-added-large-files # reject giant files (default=500kB)
      - id: detect-private-key # keep those keys safe
      - id: end-of-file-fixer # add newline at end of files
      - id: trailing-whitespace # trim trailing whitespace
  ####################
  # PYTHON
  ####################
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.21.0'
    hooks:
      - id: django-upgrade
        args: [--target-version, '5.0']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: ['--py311-plus']
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ['--config=code-examples/dj-scratch/pyproject.toml']
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--settings-file=code-examples/dj-scratch/pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--config=code-examples/dj-scratch/.flake8']
        additional_dependencies:
          [
            'flake8-broken-line',
            'flake8-bugbear',
            'flake8-builtins',
            'flake8-comprehensions',
            'flake8-pytest-style',
            'flake8-return',
            'flake8-tuple',
            'pep8-naming',
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ['--config-file=code-examples/dj-scratch/pyproject.toml']
