exclude: '.git'
default_stages: [commit]

ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: 'v0.11.0'
  #   hooks:
  #     - id: markdownlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict # validate no merge conflict strings
      - id: check-json # validate json
      - id: check-yaml # validate yaml
      - id: check-added-large-files # reject giant files (default=500kB)
      - id: detect-private-key # keep those keys safe
      - id: end-of-file-fixer # add newline at end of files
      - id: trailing-whitespace # trim trailing whitespace
  ####################
  # PYTHON
  ####################
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        args: ['--config=code-examples/common/pyproject.toml']
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--settings-file=code-examples/common/pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--config=code-examples/common/.flake8']
        additional_dependencies:
          [
            'flake8-broken-line',
            'flake8-bugbear',
            'flake8-builtins',
            'flake8-comprehensions',
            'flake8-pytest-style',
            'flake8-return',
            'flake8-tuple',
            'pep8-naming',
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: ['--config-file=code-examples/common/pyproject.toml']
