# Generated by Django 3.2.5 on 2021-08-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("edition", models.CharField(max_length=255)),
                ("release_year", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("name", "edition"), name="core_book_unique_name_edition"
            ),
        ),
    ]
