# Generated by Django 3.2.9 on 2021-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolbox",
            name="tools",
            field=models.ManyToManyField(to="zen.Tool"),
        ),
    ]
