version: '3'

services:
  db:
    image: postgres
    ports:
      - '5434:5432'
    # w/o volumes, db is reset on dc down and back up (dc restart has no effect)
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

#   api:
#     build: .
#     ports:
#       - '8000:8000'
#     volumes:
#       - .:/app
#     depends_on:
#       - db

volumes:
  postgres_data:
