[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "mysite.settings"
django_debug_mode = true
python_files = "tests.py test_*.py"
# norecursedirs = []  # apps to exclude from pytest runs
addopts = ["--verbose", "-s"]

[tool.black]
target-version = ["py311"]
include = '\.pyi?$'
# change to extend-exclude on new release
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
)/
'''
# files in this dir are ignored by pre-commit
force-exclude = '''
/(
  migrations
)\
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
remove_redundant_aliases = true

# this was ported from mypy.ini and hasn't been tested so may be broken
[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true
