# Generated by Django 4.0.5 on 2022-06-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")], db_index=True
                    ),
                ),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
