# Generated by Django 4.1.4 on 2022-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customsort", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["priority", "title"], name="customsort__priorit_d85883_idx"
            ),
        ),
    ]
