# Generated by Django 4.1.4 on 2022-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customsort", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(fields=["priority", "title"], name="priority_title_idx"),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                models.Case(
                    models.When(priority=1, then=models.Value(1)),
                    models.When(priority=2, then=models.Value(2)),
                    models.When(priority=3, then=models.Value(3)),
                ),
                models.F("title"),
                name="priority_order_title_idx",
            ),
        ),
    ]
