# Generated by Django 5.1.2 on 2024-12-01 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import files.models
import files.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        storage=files.storages.FileStorage(),
                        upload_to=files.models.filename_factory,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "is_uploaded",
                    models.BooleanField(
                        default=False,
                        help_text="True if the file is uploaded to cloud storage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
