# Generated by Django 5.1.2 on 2024-10-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(db_default=0),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="product",
                    name="rating",
                ),
            ],
            database_operations=[],
        ),
    ]
