# Generated by Django 5.1.2 on 2024-10-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("green", "0002_remove_product_rating"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql=("ALTER TABLE green_product " "DROP COLUMN rating;"),
                ),
            ],
        ),
    ]
