[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "mysite.settings"
django_debug_mode = true
python_files = "tests.py test_*.py"
norecursedirs = []
addopts = ["--verbose", "-s"]

[tool.mypy]
# see other config values here:
# https://sobolevn.me/2019/08/typechecking-django-and-drf
# https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L101
python_version = "3.10"
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
# plugins = ["mypy_django_plugin.main"]

# breaks mypy in current repo setup
# [tool.django-stubs]
# django_settings_module = "mysite.settings"

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[tool.black]
target-version = ["py39"]
include = '\.pyi?$'
# change to extend-exclude on new release
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
)/
'''
# files in this dir are ignored by pre-commit
force-exclude = '''
/(
  migrations
)\
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
remove_redundant_aliases = true
