[project]
requires-python = "~=3.13.0"

[tool.black]
target-version = ["py313"]

[tool.ruff]
extend-exclude = [
    "*/migrations/*.py",
    "staticfiles/*",
]

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "mysite.settings"
django_debug_mode = true
python_files = "tests.py test_*.py"
# norecursedirs = []  # apps to exclude from pytest runs
addopts = ["--verbose", "-s"]

# this was ported from mypy.ini and hasn't been tested so may be broken
[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true
