# Generated by Django 5.0.2 on 2024-02-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_retired",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="product",
                    name="is_retired",
                ),
            ],
            database_operations=[],
        ),
    ]
