# Generated by Django 5.0.2 on 2024-10-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="z",
            field=models.IntegerField(null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="point",
                    name="z",
                ),
            ],
            database_operations=[],
        ),
    ]
