# Generated by Django 5.0.2 on 2024-10-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_point_z"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_point DROP COLUMN z;",
                ),
            ],
        ),
    ]
